### ISSUE TITLE
F-Droid version out-of-date

### ISSUE THREAD

**Issue by RussellAult** [bpellin/keepassdroid#115]
The current Google Play version is 2.0.6.1, while F-Droid is still on 2.0.4. The reasons can be found [here](https://f-droid.org/wiki/page/com.android.keepass) and relate to way the JNI SHA library is acquired using `prep_build.sh.`

Is this something that can easily be resolved for the next version? I currently keep the app updated via Google Play, but for FOSS I'd rather get it via F-Droid.

Thanks!

**Comment by ligi** [comment]
would also be interested behind the reasoning behind prep_build.sh - it just fetches a zip and unzips it:

```
#!/bin/sh
SHA_FILE="sha2-07-01-07.zip"

curl http://173.254.28.24/~brgladma/oldsite/cryptography_technology/sha/$SHA_FILE > $SHA_FILE
unzip $SHA_FILE -d sha

```

why not just check these files in? can't be the size

```
 ⋊> ~/g/3/k/a/s/m/jni on master ⨯ du sha -hs                                                                              01:07:58
272K	sha

```

**Comment by ka223** [comment]
Strange, still no response ... really want to know why.

**Comment by jfreax** [comment]
Any update about this problem? Due to issue #86 the old f-droid version doesn't work on Android N at all.

**Comment by bpellin** [comment]
I have no affiliation with f-droid. Feel free to grab my builds from https://github.com/bpellin/keepassdroid/releases

**Comment by jfreax** [comment]
It's a shame that you are not interested in f-droid. It's a great and important project in my opinion.

**Comment by RussellAult** [comment]
I'll second @jfreax's comment. F-Droid is a very valuable contribution to the Android FOSS ecosystem (in the same way that tools like APT are a very valuable contribution to the Linux FOSS ecosystem).

Despite not having any affiliation with F-Droid (which, as I understand it, is true of much of the software in the F-Droid repository, just as it's true of much of the software in Debian's APT repository) would you please incorporate the SHA source directly in this project anyway? I don't think it would in any way degrade the quality of the software, but it would make it easier for people who don't have access to Google Play to stay on the most recent release version.

Thanks!
