### ISSUE TITLE
Can't open keypass file in Windows having saved it within KeePassDroid.

### ISSUE THREAD

**Issue by HergestPhil** [bpellin/keepassdroid#127]
I had a working .kbd on Windows 7 (could open using KeePass Password Safe V1.31).
I copied to my mobile and opened within KeePassDroid.  I added a new entry and saved the .kdb file.
I copied the .kdb back to Windows 7, and found that I could no longer open the file.  It reports "Invalid/wrong key.", error code 0x00000004.

So saving a .kdb in KeePassDroid seems to lose compatibility of the file with other platforms.

**Comment by pancenu** [comment]
Have you test a recent version of keepass on windows?

**Comment by HergestPhil** [comment]
Seems to be working fine now.|

**Comment by pepeEL** [comment]
But what version did you use ?

**Comment by HergestPhil** [comment]
I had the latest version of KeePassDroid 2.0.6.1.  Seems a phone reboot fixed whatever the problem was?
