### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by leidongld** [bpellin/keepassdroid#134]
Sir, I download your project and import it to my Android Studio. When I press the Run 'app' button, an error occured. Details as follows.

_compiling kpd_jni.c failed.
F:\AndroidStudioProjects\keepassdroid-master\keepassdroid-master\app\src\main\jni\final_key\kpd_jni.c:39:20: fatal error: sha256.h: No such file or directory
 #include "sha256.h"_

Please help me, thank you.

**Comment by leidongld** [comment]
I change the #include "sha2.h" to #include "sha256.h" , but if it is still #include "sha2.h", the error is still there, the details are:

compiling kpd_jni.c failed.
F:\AndroidStudioProjects\keepassdroid-master\keepassdroid-master\app\src\main\jni\final_key\kpd_jni.c:39:20: fatal error: sha2.h: No such file or directory
#include "sha2.h"

**Comment by bpellin** [comment]
You need to use prep_build.sh to pull in the dependencies.
