### ISSUE TITLE
Open .kdbx Database File Fails on Android 7.0 Nougat: HashedBlockInputStream.read() returned value out of range

### ISSUE THREAD

**Issue by resolutecake** [bpellin/keepassdroid#138]
SYMPTOM
On tap OK after input password

BUG: a toaster is displayed:
**com.keepassdroid.stream.HashedBlockInputStream.read() returned value out of range -1..255: -117**
app goes back to password input

EXPECTED: database file to open

Compared versions
Android 7.0: 2.0.3 and 2.0.4: both failed
Android 4.4.4: 2.0.3: works
- Database file md5sum the same

**Comment by bpellin** [comment]
Use version 2.0.6 or later. This was fixed in that version.

**Comment by resolutecake** [comment]
Thank you, I just completed testing that, and it works.

F-Droid does not have later than 2.0.4

A failing older version can be uninstalled and replaced with apk at this link:
[https://github.com/bpellin/keepassdroid/releases/download/v2.0.6.1/app-flavor1-release.apk](https://github.com/bpellin/keepassdroid/releases/download/v2.0.6.1/app-flavor1-release.apk)
(it is from this github repository)
