### ISSUE TITLE
Opening database fails.

### ISSUE THREAD

**Issue by PriceChild** [bpellin/keepassdroid#141]
Error given is:

> com.keepassdroid.stream.HashedBlockInputStream.read() returned value out of range -1..255:-117

in a hovering notification.

This is a Nexus 5X with Android 7.0, build NRD90M

**Comment by monojp** [comment]
This is a duplicate of #86 and should be fixed in a newer version

**Comment by PriceChild** [comment]
I'm very sorry for not confirming before but yes, it's fixed now. I think half the issue was that the freedroid builds lagged google play.
