### ISSUE TITLE
f-droid building problems

### ISSUE THREAD

**Issue by monojp** [bpellin/keepassdroid#142]
Hi,
sorry for bothering with f-droid stuff, but I noticed that the version there is already outdated. I'm not the maintainer but found notes at https://f-droid.org/wiki/page/com.android.keepass#Maintainer_Notes
Can this be fixed / adapted in keepassdroid directly or do the f-droid guys need to fix this?
I would have not noticed if I wasn't trying out N which triggered the HashedBlock error from #86 and I'm afraid that bugreports / duplicates will increase if more people start using N with the outdated f-droid version
EDIT: @bpellin can you help us out with this?

**Comment by bpellin** [comment]
I checked in the dependencies to build everything without any special changes in 2.0.6.2. The ball is in f-droid's court now.

**Comment by krt16s** [comment]
@bpellin: Are the *.so in https://github.com/bpellin/keepassdroid/tree/master/app/src/main/jniLibs/ leftovers? They are rebuild when invoking gradle, but not copied over to the original place. Still present in the apk, though.

**Comment by bpellin** [comment]
Looks those were leftover from before I migrated to android studio, but they were included in the apk, and were being used due to an error in how I would building the native libraries in gradle.
