### ISSUE TITLE
Why automatically saving to google drive?

### ISSUE THREAD

**Issue by gizmo21** [bpellin/keepassdroid#157]
I opened "google drive - pref - list of saved apps" and found keepassdroid there with a 1,2kb backup. What is saved there and can I disable it somewhere?

**Comment by spikebike** [comment]
I don't see that option.  Were you possibly using keepaddroid2gdrive?

**Comment by gizmo21** [comment]
No I just have Android 6.0.1 and have only KeePassDroid installed.
I just looked a little bit more and it seems it is enabled by default with API level 23 and you as dev have to disable it in app by adding the following to your AndroidManifest.xml :
<application ...
    android:allowBackup="false">
</app>

see: https://developer.android.com/guide/topics/data/autobackup.html

**Comment by bpellin** [comment]
This stores application settings. Mostly the various check boxes under the settings menu.

You can disable this in the android settings menu. Usually under Backup, but it varies by android version.
