### ISSUE TITLE
No mention of new signing key

### ISSUE THREAD

**Issue by krbvroc1** [bpellin/keepassdroid#161]
F-droid wants me to uninstall old version and install new version 2.0.6.4 with new signing key. Where is this announced? Nothing even in the change log. How does one know this is legitimate?

**Comment by bpellin** [comment]
I have no affiliation with F-droid. They rebuild their apks from source and resign them with their keys.

It's up to you to decide whether or not you trust them.

**Comment by krbvroc1** [comment]
OK thanks.

**Comment by krbvroc1** [comment]
BTW, I installed via Play Store but F-Droid wants to update it to the newer version, thus the red flag.
