### ISSUE TITLE
KDBX 4 support

### ISSUE THREAD

**Issue by NikitaPuzyryov** [bpellin/keepassdroid#175]
Recent KeePass release (2.35) introduced a new file format: KDBX 4. It has numerous exciting cryptographic improvements.

Relevant links:
http://keepass.info/news/n170109_2.35.html
http://keepass.info/help/kb/kdbx_4.html

**Comment by thomasvnl** [comment]
+1 cause now I can't open my database on my phone without making it "less secure"

**Comment by HebrewzHammer** [comment]
+1

**Comment by obyy** [comment]
+1 it will be great :D

**Comment by va1entin** [comment]
This would be great to have. With KeePassX and KeePassDroid not supporting KDBX 4, I have to maintain two databases at the moment.

**Comment by NikitaPuzyryov** [comment]
The support has been added in 41157462585b4ca7b2726054c6ec2b93afa8a6a4

**Comment by jowave** [comment]
The website http://www.keepassdroid.com still says:

> However, KDBX version 4 is not yet supported.

As I understand it, this should be removed.
