### ISSUE TITLE
Nobody seems to be active to support this app.

### ISSUE THREAD

**Issue by Penguin-Guru** [bpellin/keepassdroid#181]
I really hope I'm wrong but there are a lot of unresolved issues here that nobody has commented on. Keypass is a very important piece of software and it is only becoming more necessary with all these web services. If anyone is active here, please mark this issue resolved so I can begin using this software with confidence.

**Comment by pradi** [comment]
what do you expect ... this software is free.
I donated twice, how often did you?

**Comment by Penguin-Guru** [comment]
I am not a programmer. When I run into problems, I have to ask for help from the community. Especially with software like this, it would be very bad to suddenly lose access to my passwords or lose confidence in their security. Because of these soft of risks, I do not want to rely on software without some support.

Thank you for posting and for donating to a good cause. :)

**Comment by pradi** [comment]
Yes, I hope that more people support this project through donations. I am not part of it, but I am a software developer and I know how much work it is to support a free project in my free time.

So if you need support take a look at https://www.password-depot.de/ or other paid solutions.
Then you have to spend something like 40€ in the year. If you like KeePasDroid, you can spend also something here to support.

**Comment by Penguin-Guru** [comment]
Alright, I will look at the products you suggested. KeePass for Windows is very nice and I do prefer free and open-source software when it is possible. Unfortunately, I simply don't have the technical skill to fix every problem myself, and I do often run into problems... Some free software projects have very good user support, either by the developer(s) or from the community, that is why I asked this question. It is good if donations help develop the project but helping users become comfortable with the software and resolve their problems is also an important was to contribute. Even if the software is perfect, users will always find problems.

Thank you again for taking the time to talk with me. I still hope to use KeePass but it is always good to know of the other options. Perhaps I will try using both options if it is necessary, then I would have the paid service for emergencies until I learn more about KeePass and Android.

**Comment by Penguin-Guru** [comment]
I am going to close this issue now. I have found some basic support from the main KeePass project's SourceForge forum. If anyone needs support for this project in the future, it may be worth asking there as well as here. :)
