### ISSUE TITLE
Can not remove group and move item in KeepassDroid!

### ISSUE THREAD

**Issue by c0001** [bpellin/keepassdroid#210]
Hi Provider:
     I really like the app you build ,but I've found three questions of it which I hope to rebuild into this app.
1) Add the function of removing group.
2) Add the function of moving item to another item(p.s. like one group or key can be moving into another group .
3) Add the  function of sorting item by yourself  without the default sorted style.
4) Why don't you make the app as whole function as the one on PC?

**Comment by serpien73** [comment]
Yes - this is a must-have.

**Comment by c0001** [comment]
I close this issue for the obsolete reason
