### ISSUE TITLE
Keepass no longer works on Samsung S7

### ISSUE THREAD

**Issue by philosifer** [bpellin/keepassdroid#214]
Following a recent update for the Samsung S7, Keepass files cannot be opened reliably or saved. There seem to be several issues

1) Attempting to open either kdb or kdbx files from the my files app results in a message "Unable to open file" as their are no apps installed that support the file type. Clicking the search button and finding keepass droid in the play store does then get you to the login screen but then
2) After entering the password for the database the error "Database format not recognised" appears. The files however still open fine from the PC version of Keepass.

Removing and reinstalling keepass doesn't fix the problem. I checked and Keepassdroid has the "storage" permission which seems to be all it wants. My phone is currently report Android as version 7.0, security patch level 1 July 2017.

**Comment by mvaughn3** [comment]
I also have a Samsung S7, android version 7.0, with security patch July 1, 2017. I am not able to replicate these issues.

Perhaps the copy of your database local to your android device is at fault?

**Comment by jasoncollege24** [comment]
if you're loading from a local copy that is on your phone, it could be a corrupted copy.

Maybe try putting the encrypted database file into a cloud service (like onedrive, or dropbox) and access it that way. This allows for loading from any device connected to that cloud, and makes sure you're always working with the live, and updated version of your database

**Comment by philosifer** [comment]
The file worked fine with a different keepass program. Then again it also worked fine with my wife's S7 which seemed to be on the same version. I'm going to close this issue as I can't reproduce it and don't expect to make any progress on it.

**Comment by jasoncollege24** [comment]
On my J3, I had to reload the key file, and database manually each time i accessed the app, even if it was already running in the background. when I started doing that, it worked fine. Unlike the PC version, it doesn't seem to use the same key file/database from the previous use, even though the fields are populated.

**Comment by amjdev** [comment]
I can open kdb and kdbx files on my S7 Edge, but get an error writing to the database when adding a new entry (KeePassDroid version 2.2.0.9). I think the bug is related with the path stored when you choose a new database file. When you choose the new database file, the last two '/' are replaced by %3A and %2F respectively. The workaround I've tested is to put back the '/' and check the "default database" mark. Doing that it works like a charm again. Hope it helps.
