### ISSUE TITLE
Crash on x86 while creating Database key

### ISSUE THREAD

**Issue by hannemann** [bpellin/keepassdroid#22]
Hi,

If i open up Keepassdroid on my x86 Tablet with ICS 4.3 it crashes after typing in my Password. I attached some hopefully helpful output from catlog.

04-09 10:23:02.361 D/dalvikvm(5231): Trying to load lib /data/data/com.android.keepass/lib/libfinal-key.so 0xa066df20
04-09 10:23:02.361 D/dalvikvm(5231): Added shared lib /data/data/com.android.keepass/lib/libfinal-key.so 0xa066df20
04-09 10:23:02.361 F/libc    (5231): Fatal signal 11 (SIGSEGV) at 0x010001a0 (code=1)
04-09 10:23:02.561 I/DEBUG   (1571): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-09 10:23:02.561 I/DEBUG   (1571): Build fingerprint: 'generic_x86/wetab/wetab:4.0.3/IML74K/eng.corvus.20120315.155503:eng/test-keys'
04-09 10:23:02.561 I/DEBUG   (1571): pid: 5231, tid: 5273  >>> com.android.keepass <<<
04-09 10:23:02.561 I/DEBUG   (1571): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 010001a0
04-09 10:23:02.561 I/DEBUG   (1571):  eax f9faff0d  ebx 01000004  ecx 00000010  edx 00000000
04-09 10:23:02.561 I/DEBUG   (1571):  esi a066d960  edi 000000ba
04-09 10:23:02.561 I/DEBUG   (1571):  xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000 xss 0000007b
04-09 10:23:02.561 I/DEBUG   (1571):  eip 9af1cfc8  ebp 5bde595b  esp 9b0307c0  flags 00010246
04-09 10:23:02.711 I/DEBUG   (1571):     #00  eip: 9af1cfc8  /data/data/com.android.keepass/lib/libfinal-key.so (aes_encrypt_key256)
04-09 10:23:02.711 I/DEBUG   (1571):     #01  eip: ffffffff   (aes_encrypt_key256)
04-09 10:23:02.711 I/DEBUG   (1571):     #02  eip: ffffffff   (aes_encrypt_key256)
04-09 10:23:02.711 I/DEBUG   (1571):     #03  eip: ffffffff   (aes_encrypt_key256)
04-09 10:23:02.711 I/DEBUG   (1571):     #04  eip: ffffffff   (aes_encrypt_key256)
04-09 10:23:02.711 I/DEBUG   (1571):     #05  eip: ffffffff   (aes_encrypt_key256)
04-09 10:23:02.711 I/DEBUG   (1571):     #06  eip: ffffffff   (aes_encrypt_key256)
04-09 10:23:02.711 I/DEBUG   (1571):     #07  eip: ffffffff   (aes_encrypt_key256)
04-09 10:23:02.711 I/DEBUG   (1571): stack: 
04-09 10:23:04.731 I/BootReceiver(1630): Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
04-09 10:23:04.741 W/InputDispatcher(1630): channel 'a0b244a0 com.android.keepass/com.keepassdroid.fileselect.FileSelectActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x8
04-09 10:23:04.741 E/InputDispatcher(1630): channel 'a0b244a0 com.android.keepass/com.keepassdroid.fileselect.FileSelectActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-09 10:23:04.741 D/Zygote  (1573): Process 5231 terminated by signal (11)
04-09 10:23:04.761 D/dalvikvm(1630): GC_FOR_ALLOC freed 1660K, 21% free 11427K/14407K, paused 25ms
04-09 10:23:04.761 I/WindowManager(1630): WIN DEATH: Window{a0a4c868 com.android.keepass/com.keepassdroid.PasswordActivity paused=false}
04-09 10:23:04.761 I/ActivityManager(1630): Process com.android.keepass (pid 5231) has died.
04-09 10:23:04.761 W/ActivityManager(1630): Force removing ActivityRecord{a0a86e28 com.android.keepass/com.keepassdroid.PasswordActivity}: app died, no saved state
04-09 10:23:04.771 W/InputDispatcher(1630): Attempted to unregister already unregistered input channel 'a0b244a0 com.android.keepass/com.keepassdroid.fileselect.FileSelectActivity (server)'
04-09 10:23:04.771 E/InputDispatcher(1630): Received spurious receive callback for unknown input channel.  fd=264, events=0x8
04-09 10:23:04.771 W/InputDispatcher(1630): channel 'a0a6f078 In Bearbeitung… (server)' ~ Consumer closed input channel or an error occurred.  events=0x8
04-09 10:23:04.771 E/InputDispatcher(1630): channel 'a0a6f078 In Bearbeitung… (server)' ~ Channel is unrecoverably broken and will be disposed!
04-09 10:23:04.771 W/InputDispatcher(1630): Attempted to unregister already unregistered input channel 'a0a6f078 In Bearbeitung… (server)'
04-09 10:23:04.771 I/WindowManager(1630): WINDOW DIED Window{a0b244a0 com.android.keepass/com.keepassdroid.fileselect.FileSelectActivity paused=false}
04-09 10:23:04.771 W/WindowManager(1630): Failed looking up window
04-09 10:23:04.771 W/WindowManager(1630): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@a0a92970 does not exist
04-09 10:23:04.771 W/WindowManager(1630): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7156)
04-09 10:23:04.771 W/WindowManager(1630): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7147)
04-09 10:23:04.771 W/WindowManager(1630): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1529)
04-09 10:23:04.771 W/WindowManager(1630): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:417)
04-09 10:23:04.771 W/WindowManager(1630): 	at dalvik.system.NativeStart.run(Native Method)
04-09 10:23:04.771 I/WindowManager(1630): WIN DEATH: null
04-09 10:23:04.771 I/WindowManager(1630): WIN DEATH: Window{a0a6f078 In Bearbeitung… paused=false}
04-09 10:23:04.771 I/WindowManager(1630): WINDOW DIED Window{a0a6f078 In Bearbeitung… paused=false}
04-09 10:23:04.791 I/ActivityManager(1630): Start proc com.android.keepass for activity com.android.keepass/com.keepassdroid.fileselect.FileSelectActivity: pid=5278 uid=10102 gids={1015}
04-09 10:23:04.801 I/dalvikvm(5278): Turning on JNI app bug workarounds for target SDK version 10...

**Comment by bpellin** [comment]
I believe this was fixed in version 1.99.9.
