### ISSUE TITLE
fingerprint authentication

### ISSUE THREAD

**Issue by eliasjonsson023** [bpellin/keepassdroid#226]
I would love to see fingerprint authentication instead of entering a password to log in.

**Comment by crr0004** [comment]
There is a branch with the support for fingerprint authentication (last commit 58141bd6fa92dc4f0773fcf8949d0b65821453f2).

I have built it and tested it, works pretty well, couple of bugs which need working out.

**Comment by eliasjonsson023** [comment]
Is there an ETA on when we can expect to thrive in this wonderful feature?

**Comment by ted1735** [comment]
Yes please awesome!

**Comment by crr0004** [comment]
If you're desperate, I have merged it into my [fork](https://github.com/crr0004/keepassdroid) and put a binary APK in the releases. I'm maintaining my own fork while the original author is absent

**Comment by eliasjonsson023** [comment]
Yes, I'm desperate. Now how do I get hold of the .apk file?

**Comment by crr0004** [comment]
I have my apk releases here: https://github.com/crr0004/keepassdroid/releases

Download the latest one. Keep in mind there may still be bugs in it. If you spot any, let me know and I'll fix them.

**Comment by bpellin** [comment]
This feature is now present in the beta channel in version 2.2.0.0, if anyone wishes to opt in:
https://play.google.com/apps/testing/com.android.keepass
