### ISSUE TITLE
Fingerprint not working on Huawei

### ISSUE THREAD

**Issue by pepeEL** [bpellin/keepassdroid#231]
Hi
I installed latest version 2.2.0.1 app on my Huawei P10 with Android 7.0. I want start user Fingerprint to login to base but i can not. Fingerprint not reaction. Sometime show Fingerprint problem.
Please help me.

**Comment by crr0004** [comment]
I know some phones don't correctly report they have a fingerprint sensor. I know the Samsung S5 does this. I'll have a look at adding some better reporting for this.

**Comment by pepeEL** [comment]
On today version 2.2.0.2 is still problem. Still i get info "Fingerprint problem"

**Comment by heavyhdx** [comment]
Same issue on 2.2.0.2 on Google Pixel with Android 8.1.0

**Comment by pepeEL** [comment]
Any news ?

**Comment by pepeEL** [comment]
still not working...

**Comment by pepeEL** [comment]
Today i installed version 2.2.0.4 and Fingerprint still not working.

**Comment by Dempsek** [comment]
I have a Huawei P9 and the fingerprint option does not work, other apps with the same feature works -  Android 6
I tried my Samsung Galaxy tab S2 tablet and the fingerprint is not working - Android 7.
KeyPassDroid 2.2.04

**Comment by crr0004** [comment]
Thanks for the continued updates pepeEL. I still intend to look at this
however haven't had a chance.

Thanks for confirming it's not a hardware issue Dempsek

pepeEL you've made sure to enroll a fingerprint on your phone and
everything?

**Comment by pepeEL** [comment]
I use my Fingerprint to unlock phone and login to other app. And Fingerprint works perfect.

**Comment by pepeEL** [comment]
I installed version 2.2.0.6 and still fingerprint not working. Show icon fingerprint but i click on this and nothing...

**Comment by bpellin** [comment]
The finger print icon is not clickable. You should enter the correct
password then press the fingerprint sensor.

**Comment by Dempsek** [comment]
It's working on my phone but not as expected.  Entering my password and then using the fingerprint sensor opens the file and while the app is open it will reopen a locked database.
When the app opens it says password not stored for this database, once the password is entered and fingerprint used it says listening for fingerprints.
Most people would expect the fingerprint sensor just to open the file/database or to have the option to setup to use fingerprint login.

**Comment by pepeEL** [comment]
Ok works OK. But use it for new user is not simple. Should be in settings configuration for fingerprint
