### ISSUE TITLE
New fork for F-Droid

### ISSUE THREAD

**Issue by J-Jamet** [bpellin/keepassdroid#236]
Hello bpellin, 
I wanted to know if I could push a keepassdroid fork application named KepassDX on F-Droid and the other stores. I did a lot of change, like the implementation of material design and I will put the autofill. I really wanted to make a personal application that's why I did not want to merge. But of course I keep all the contributors and the GPL license, I just wanted to know if it was not a problem for you.
Thx for your awesome work! :)

**Comment by bpellin** [comment]
You are definitely welcome to.

Feel free to send pull requests too for improvements, as well.
