### ISSUE TITLE
Unsupported database version for KeyPass 2.37 .kdbx file

### ISSUE THREAD

**Issue by emanfantastic** [bpellin/keepassdroid#237]
As stated on the website, kdbx version 4 is not yest supported. This is a feature request only.

KDBX File Version: 4
Platform: Android 7.1.1 on Motorola Moto Z Force
KeePass Version: 2.37
KeePass Droid Version: 2.0.6.4
Error Message: Unsupported database version
Authentication method: Password + Key file

**Comment by bpellin** [comment]
Fixed in KeePassDroid version 2.2.0.0 or greater.
