### ISSUE TITLE
Menu shifts to extreme right edge of screen when searching.

### ISSUE THREAD

**Issue by wellread1** [bpellin/keepassdroid#239]
When the search dialog is active the search box is shifted to the right leaving wasted space to the left, while controls to the right of the search box are shifted to the far right leaving the menu at the extreme right of the screen where it is inaccessible.  This is minor GUI glitch because canceling the search restores the header.  I have attached a screenshot to illustrate the issue.  KeePass2Android v1.03-pre3 on Android 7.1.1 on the Essential Phone (PH-1).

![keepass2android](https://user-images.githubusercontent.com/13069300/33154935-ecab0874-cfa0-11e7-9d8d-c2fde3cd0b52.png)

**Comment by bpellin** [comment]
You'll want to post this over here:
https://github.com/PhilippC/keepass2android

**Comment by wellread1** [comment]
Sorry about that.
