### ISSUE TITLE
Inappropriate font for password display

### ISSUE THREAD

**Issue by mpathy** [bpellin/keepassdroid#24]
The password display function is almost useless because you use sans-serif font for display the password.

Where 0 and O are already hard to distinguish, the letters l and I are impossible to distinguish.

I can provide a screenshot if you want.

Please change the font style of the password display from sans-serif to monospace or at least provide a option to change the font-style or the font itself in the settings.

**Comment by bpellin** [comment]
A new font for passwords was added in 2.0.1.
