### ISSUE TITLE
Where is Dropbox support gone ?

### ISSUE THREAD

**Issue by daisy-day** [bpellin/keepassdroid#243]
After most recent update the support for Dropbox located files has been made unavailable.
I am an HTC A9s user

**Comment by bpellin** [comment]
I think I inadvertently made the application always try to use the storage access framework on KitKat and later. DropBox doesn't support it.

I'll look at pushing out an update to make this respect the setting under the Application Settings menu again.

**Comment by transmogrifier** [comment]
I am experiencing this issue also on Pixel 2. I have version 2.2.0.6. I can select a key file from DropBox but I cannot open the database file itself from DropBox. I was however able to open the database file from DropBox by going to the DropBox app and then opening the file from there and selecting KeepPassDroid as the default app. However after saving the file, the file got corrupted. I see that there is a different issue about that.

**Comment by bpellin** [comment]
Fixed in version 2.2.0.7.

Make sure you have the Storage Access Framework option disabled in the settings menu.

**Comment by transmogrifier** [comment]
Tested with 2.2.07. DropBox access is working now.
