### ISSUE TITLE
Latest Build causing Bootloop in CM12

### ISSUE THREAD

**Issue by DonDante** [bpellin/keepassdroid#249]
Latest build crashes CM12 during update.
CM12 runs in bootloop, can only be stopped by deleting keepassdroid app in TWR.
Causes:
AAPT2 option in latest Android Studio
If you need to build with 3.0 but are running into this bug you can disable aapt2 using -Pandroid.enableAapt2=false on the command line when doing your build.

Please fix

**Comment by rogers1106** [comment]
Same here with CM13. Nova Launcher and Twidere had the same problem last month.

**Comment by bpellin** [comment]
Android build tools 27.0.1 is supposed to work around this bug in CM/Lineage. 2.2.0.9 uses this version of the build tools.

**Comment by rogers1106** [comment]
Where did you get 2.2.0.9?

**Comment by rogers1106** [comment]
Oops, found it. It's working with LineageOS 13.0

**Comment by DonDante** [comment]
Not working with CM12 or CM13.
Was running CM12 and flashed CM13.
Same thing:
As soon as newest Google Play version of keepassdroid is downloaded and installing it bootloops.
Had the same issue with BlueMail until they fixed AAPT2.
