### ISSUE TITLE
How can I delete saved passwords encrypted with fingerprint?

### ISSUE THREAD

**Issue by hach-que** [bpellin/keepassdroid#254]
I encrypted my password to try out the feature, but now I can't find a way to remove the saved encrypted password.

**Comment by Mkwebman** [comment]
I would like to be able to reset password too as it has stored the wrong password

**Comment by mkohler** [comment]
I found that I could reset the password by uninstalling and reinstalling KeePassDroid.

**Comment by rafasc** [comment]
The workaround seems to be either re-encrypting an incorrect password or clean data and cache.
