### ISSUE TITLE
Active Development?

### ISSUE THREAD

**Issue by hap124** [bpellin/keepassdroid#257]
I have seen lots of comments on reddit etc that this app is not developed anymore. Being new to github I don't know how to check and as far as I can tell I don't see any recent comments from the owner. Can anyone tell me A. If it's active and B. how one checks that here?

Thank you

**Comment by crr0004** [comment]
By the sounds of it you're new to Github, so welcome!

Yes this is still under active development, there was a period earlier this year where it looked it like it wasn't. However new features like fingerprint unlocking have recently been added. There has also been some bug fixes. For any project on github you can check when the most recent commit was made on the project page, sample in the following image
![Latest commit](https://i.imgur.com/dLQqYvq.png)

**Comment by hap124** [comment]
@crr0004 thanks for the explanations and noob friendliness :)

**Comment by crr0004** [comment]
No worries! We all start somewhere.
