### ISSUE TITLE
Enhancement Allow easy switch to previous keyboard

### ISSUE THREAD

**Issue by cverbiest** [bpellin/keepassdroid#280]
keepassdroid lets you switch to its own keyboard very easily but AFAIK there is no easy way to return to the previous keyboard.
It would be very nice to have a key that opens keyboard selection dialog allowing users to select their usual keyboard.

**Comment by J-Jamet** [comment]
You have been misled, there is no keyboard with Keepassdroid.

**Comment by cverbiest** [comment]
Sorry, wrong repo was for https://github.com/PhilippC/keepass2android
