### ISSUE TITLE
No longer in the Play Store?

### ISSUE THREAD

**Issue by ffes** [bpellin/keepassdroid#296]
I wanted to give my coworkers a link for them to install KeePassDriod, but I cannot find it anymore in the Play Store.

Is this a known issue? Is it temporary?

**Comment by ffes** [comment]
Just to be sure, this is the URL I checked:

https://play.google.com/store/apps/details?id=com.android.keepass

**Comment by pjao** [comment]
Same here... any idea what had happen?

**Comment by muzzar78** [comment]
Same for me.

**Comment by ffes** [comment]
It is a pity, because I need to give a Play Store link to my coworkers tomorrow.

So unfortunately I need to investigate an alternative 😢

**Comment by bpellin** [comment]
It is back up now.

**Comment by ffes** [comment]
Thanks a lot! You saved my day 👍
