### ISSUE TITLE
Encoding fix

### ISSUE THREAD

**Issue by FoxP** [bpellin/keepassdroid#309]
Hello,

There is a `\u00A0` string at the end of:
> Entrez un mot de passe et/ou un fichier de clé pour ouvrir la base de données

![screenshot_20180729-120003](https://user-images.githubusercontent.com/16615901/43365147-5e55c572-9328-11e8-8ac7-1732ed0237b8.png)

French language here.

I'm using the latest stable version from F-Droid.

BTW, thanks for KeePassDroid! :+1:

**Comment by bpellin** [comment]
This has since been fixed.
