### ISSUE TITLE
Pixel 4 dropping physical fingerprint scanner, what is impact to keepass2android

### ISSUE THREAD

**Issue by df03438** [bpellin/keepassdroid#374]
The Pixel 4 will not have a physical fingerprint scanner but use faceid sensor scanning for phone unlocking. What impact will this have on your app? Will faceid scan work automatically as a replacement? Please investigate and let us know what solutions you come up with.

**Comment by mikeluby** [comment]
As a Pixel 4 / Keepassdroid user, the application still works but will require you to type password to the keepass database each time.

I hope at some point soon the Biometric API is implemented to support face unlock

**Comment by Braintelligence** [comment]
Well the API is even mandatory for new apps by now... https://www.google.com/amp/s/www.xda-developers.com/google-pixel-4-users-wait-developers-add-face-unlock-support/amp/

**Comment by StevenNexus** [comment]
Can confirm that face unlock on the PIxel 4 does not work with the current version of KeePassDroid. Have to use password.

Hope the Biometric API is implemented to allow support for all types of Biometric unlocking.

**Comment by bpellin** [comment]
KeePass2Android is a different app, but the beta version's of KeePassDroid that I've posted recently support the biometric API.
