### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [bpellin/keepassdroid#384]
Thoughts? https://f-droid.org/wiki/page/com.android.keepass/lastbuild_183

**Comment by bpellin** [comment]
From the error messages it seems like f-droid's build server doesn't have the version of the ndk installed that it is trying to use.

**Comment by licaon-kter** [comment]
It is available, if the metadata asks for it, else it ends up with version 12


Anyway, fixed already: https://gitlab.com/fdroid/fdroiddata/-/commit/46b8829d06c6e788e3193609a04588f87ae7381c
