### ISSUE TITLE
Crash when trying to open an entry

### ISSUE THREAD

**Issue by dmak** [bpellin/keepassdroid#389]
The issue seems to be similar to issue #346 but I am not sure because once I slightly modify the problematic entry description it can be opened without a problem. So it could be a combination of description length and presence of a reference.

To reproduce the crash open below DB and open the only entry in it.

Test DB: [test.zip](https://github.com/bpellin/keepassdroid/files/4281283/test.zip)
Password: 123

**Comment by bpellin** [comment]
Fixed in 2.5.7.
