### ISSUE TITLE
Can't get to keepassdroid via kdbx file in Dropbox app 

### ISSUE THREAD

**Issue by james-baker** [bpellin/keepassdroid#408]
Repro:
1. Open the dropbox app to "Home" screen
2. Tap on a kdbx file in the Recent or Starred file list

Expected: Tapping on a kdbx file should take me to the KeePassDroid app (which usually lists a filename of the form content://com.dropbox.android.FileCache/filecache/<guid>)
Actual: When I tap the kdbx file, it flashes out to "Drive PDF Viewer" momentarily, which (presumably) errs immediately and bounces back to Dropbox.

3. Tap the 3-vertical-dots icon on the file to access more options
4. Tap the "Open with..." option

Expected: I should see KeePassDroid as an option in the popup list, and be able to select it and then tap "Always" or "Just once"
Actual: The only option is "Drive PDF Viewer".

This regressed as of a few-to-several days ago for me.  KeePassDroid seems to have lost its association with .kdbx files, as far as Dropbox is concerned - doesn't show up in the 

Things it is not:

- ...inside the PBD app itself: The app still opens, and can open kdbx files via the KPD folder-icon UI (which intent-links to the "Files" explorer, and lets me select e.g. content://com.android.providers.downloads.documents/<path>).
- ...completely disassociated with .kbdx on an OS level: Opening the Files explorer app directly, when I select a kdbx it gives an "Open with..." that includes KeePassDroid (though no "once or always" flow).

Environment: Pixel 4 phone, there are both Dropbox and KeePassDroid updates in my recent history

Doesn't quite seem related to https://github.com/bpellin/keepassdroid/issues/395

**Comment by james-baker** [comment]
Discovered a workaround! And the original cause appears more likely to be on the Dropbox side.

Tap the 3-vertical-dots icon on the file to access "more options"
Select "Make available offline"
Now tap on the kdbx file again to open it
KeePassDroid appears in an app chooser list!
Open the file, with KeePassDroid ("always")

At this point, going back to Dropbox and undo-ing the "Make available offline" *still* leaves the problem fixed!

**Comment by proxybox** [comment]
Thanks! I also solved this issue independently but found the error repeated even with the kdbx file marked offline. Once I switched it off and switched back to offline again did I restore the keepassdroid app as an option again. Something strange is happening with dropbox.

**Comment by proxybox** [comment]
james-baker is yours holding? I notice that I have to perform the offline/online dance routinely. I can't determine what makes it change.

**Comment by james-baker** [comment]
Same @proxybox , mine does not "hold" either. I have no idea how Dropbox is messing up the file type association.

**Comment by kitingChris** [comment]
Dropbox insists that it is keepassdroids fault :facepalm: 
https://www.dropboxforum.com/t5/Dropbox-installs-integrations/Cannot-anymore-open-kdbx-file-stored-in-Dropbox-with/m-p/427607/highlight/true#M94326

**Comment by proxybox** [comment]
They fixed it!!! I've been using a cached version to open the file and periodically doing the offline/online switch to reactivate the kdbx file to dropbox so it would stay updated. I tried it straight from dropbox recently and it's holding up now. Take a look and you'll see its finally working like before.
