### ISSUE TITLE
password not saved with biometrics

### ISSUE THREAD

**Issue by nanakinoir** [bpellin/keepassdroid#409]
Steps to reproduce:

Precondition - updated kdbx file on PC with new master password, synced Google Drive on mobile device with updated kdbx file

1. Open KeePassDroid, tap "Cancel" when prompted for fingerprint
2. Tap "Clear Stored Password"
3. Enter new password, check "Save password with biometrics", tap "Ok"
4. Prompt appears to "Save Password" with fingerprint, scan fingerprint on device
5. Database is opened and "Encrypted password saved" message appears at the bottom

-All is good at this point

6. Close/Exit KeePassDroid, reopen KeePassDroid
7. Prompt appears to "Open Database" with fingerprint, scan fingerprint on device
8. Database fails to open with message "A password or keyfile is required"
9. Password field is empty

-At this point I have to repeat steps 3-5 every time I open the app since password does not appear to be saved using fingerprint and the password field is not being populated. Even when I tap "Open Database" button, it just repeats steps 7-9.

This worked before. Am I missing something?

App version: 2.5.11
OS version: Android 10 (QP1A.191005.007.A3)

**Comment by nanakinoir** [comment]
Reverting to 2.5.8 seems to have resolved the issue, thus this might be a bug introduced in 2.5.11

**Comment by bpellin** [comment]
Thanks for the detailed replication steps. I accidentally introduced an issue that causes the app to always store an empty password.

**Comment by bpellin** [comment]
Fixed in v2.5.12.
