### ISSUE TITLE
KeePass 2.5.12

### ISSUE THREAD

**Issue by Nick1972** [bpellin/keepassdroid#412]
On the new version of KeePass 2.5.12  , I now have to press the OK button before i can finger print
entry. I have rolled back to an earlier version when i can just get in with my fingerprint.

ZTE Axon 7 Mini (B2017G) , Android 7.1.1
 Thanks.

**Comment by bpellin** [comment]
Automatic prompting makes it difficult to log in on phones that have a fingerprint sensor embedded in the front screen. So, it's no longer the default. You can re-enable this with the "Automatic biometric login" option on the settings screen.

**Comment by Nick1972** [comment]
I didn't know this, thanks. I shall try it out. Thanks for the reply :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
