### ISSUE TITLE
compatibility with keepass key creation v2

### ISSUE THREAD

**Issue by Development-Person** [bpellin/keepassdroid#438]
I recently switched from keepassx to keepassxc on windows and: 
- updated my database to KDBX 4.0
- generated a new .keyx file to replace the previous .key file. 

This seems to have broken compatibility with keepassdroid (as well as keepass2android). 

I tested by creating a new database using keepassxc and got the following results:
- new 4.0/3.1 database with no key ✅ compatible with keepassdroid 
- new 4.0/3.1 database with .keyx or .key ❌ compatible with keepassdroid and removing the key did not solve the issue (kept getting invalid database error in keepassdroid)

Throughout this whole time the databases worked in keepassxc on windows. 

So it seems like this is something to do with keepassxc creating .key/x files and/or modifying the .kdbx on key creation in a way that keepassdroid does not like?

**Comment by Development-Person** [comment]
I tried creating another database + key in keepass password safe (which gives more options on key creation) and it looks like version 2 of the key creator is incompatible with both keepassdroid and keepass2android. creating a v1 key works.
![image](https://user-images.githubusercontent.com/73729287/104828392-13d93f80-58bd-11eb-83af-0117e4bf1e2d.png)

**Comment by J-Jamet** [comment]
This new key format requires to change the XML parser in order to check the version number and to make the hexadecimal hash of the filled key. It's not easy, I made the modifications on my fork (KeePassDX) in Kotlin, you can get inspiration from it if you want compatibility with this new format on KeePassDroid.

**Comment by Development-Person** [comment]
Thanks for letting me know! This is outside of my skillset but someone else might want to take it up? I'll check out KeePassDX!

**Comment by bpellin** [comment]
This will be fixed in version 2.5.15, which will be available in the play store in the near future if you join the beta track.
https://play.google.com/apps/testing/com.android.keepass
