### ISSUE TITLE
Empty KDF UUID: file corruption

### ISSUE THREAD

**Issue by antelle** [bpellin/keepassdroid#457]
Hi! I'm the author of KeeWeb, a fork of KeePass for web and desktop.

I came across this issue today: https://github.com/keeweb/keeweb/issues/1828, which shows that KeePassDroid doesn't always write `$UUID` field in the [extensible KDF](https://keepass.info/help/kb/kdbx_4.html#extkdf) header section. Different KeePass clients, including KeePass itself, generate errors when they see such file, so I assume, the field is mandatory and you should add it, so that the format keeps being compatible.

Not sure if this happens always or depends on something, you can ask @guifsdev who originally reported the issue.

**Comment by bpellin** [comment]
I think it's an issue with how KeePassDroid handles reading in a KDBX 3 database and a change is made that requires the format to be changed to KDBX 4.

**Comment by bpellin** [comment]
Fixed in 2.5.17.
