### ISSUE TITLE
Update Bouncy Castle (CVEs)

### ISSUE THREAD

**Issue by Neustradamus** [bpellin/keepassdroid#475]
@bpellin: Can you update Bouncy Castle?

There are a lot of CVEs.

Thanks in advance.

**Comment by bpellin** [comment]
Fixed in 2.6.0.

**Comment by Neustradamus** [comment]
@bpellin: Thanks for the last update from you!
- https://github.com/bpellin/keepassdroid/blob/master/app/build.gradle#L61

There is a new version 1.72 from 25 september 2022, can you look too?

Thanks in advance.
