### ISSUE TITLE
'Pre-release' tag for 10 last releases ?

### ISSUE THREAD

**Issue by Saroumane** [bpellin/keepassdroid#503]
Hello, I would like to know why the 10 last releases are tagged as 'pre-release' ?
Latest without this tag  is 2.5.17, from 2021. 
Is it really advised to stick to 2.5.17 for daily use ?

**Comment by bpellin** [comment]
I mark them as pre-release when I upload them as beta to the play app store. However, I usually forget to mark them as no longer pre-release when I promote them to general release. 2.6.8 is the recommended version.
