### ISSUE TITLE
Critical bug with cyrillic passwords

### ISSUE THREAD

**Issue by Kondra007** [bpellin/keepassdroid#64]
When setting cyrillic password to database, only length of password is checked.
Example: database pass "маша", all 4-letter pass are treated as ok: "петя"," окно","ядро"...

**Comment by LazyKent** [comment]
Confirmed.

**Comment by bpellin** [comment]
Does this happen with .kdb databases, .kdbx or both?

**Comment by LazyKent** [comment]
I found the bug using a .kdb database created by KeePassX 0.4.3 (Linux, openSUSE).

Just tested. The bug is worse. I see the same behavior in KeePassX 0.4.3 itself. At least in a Linux version.

**Comment by Kondra007** [comment]
Tested with .kdbx - confirm bug.
Not tested with .kdb

**Comment by hulah00p** [comment]
Mobile is Android 6 not stock
.kdb, created with keepassdroid 2.0.3 with 4-letter cyrillic password(same as Kondra007 in first message)

Desktop system is Windows 7 SP1
keepassdroid opened it easy with random 4 letter password
KeePass-1.29-1 cant open it with real or random 4 letter password, gives "Invalid/wrong key, Error code 0x00000004"
KeePassX-2.0 can import it with fake password

.kdbx, created with KeePassX-2.0 with password "test"
I opened it with keepassdroid and changed password to "жопа"
After that KeePassX-2.0 AND keepassdroid can't open it with random 4-letter  cyrillic password, only with "жопа" as password.

**Comment by bpellin** [comment]
The root cause is that the .kdb file format only supports Latin1 characters. So, I don't think you'll be able to use Cyrillic characters with it successfully.

I'll add a warning to keepassdroid to prevent people from using them with kdb files.

**Comment by Kondra007** [comment]
@bpellin Is it possible to create kdbx files via KeePassDroid?

**Comment by bpellin** [comment]
Oops, i thought it was, but it looks like I never implemented it. Added to my TODO list.

You can create one on the desktop app, and read and edit it in KeepassDroid today.
