### ISSUE TITLE
Open kdb with any password on Russian coinciding count of characters.

### ISSUE THREAD

**Issue by isadchenko** [bpellin/keepassdroid#71]
Open kdb with any password on Russian coinciding count of characters.
Step to reproduce:
1. Create kdb 
2. Input password and re-password for kdb some pass in RU locale ex. 'пароль'
3. Open kdb and input password any in RU locale with same count of characters ex. 'вывыпр'
4. Profit
This is a serious security hole

**Comment by bpellin** [comment]
Dup with #64
