### ISSUE TITLE
Read failure EBADF

### ISSUE THREAD

**Issue by micalb61** [bpellin/keepassdroid#80]
Just updated the app and can't open my kdbx any more, local or gdrive I always get a Bad file descriptor error

**Comment by landstander668** [comment]
I'm seeing this as well, on a Nexus 6P running Android 6.0.1 (February security update). Unfortunately, it appears that KeePassDroid is no longer able to open *any* kdbx file (I haven't tested the older kdb format, as I no longer have any such files available).

Is the older 2.0.4 APK archived anywhere? I need to restore access to my password database fairly soon...

**Comment by micalb61** [comment]
I am on Nexus 5 Android 6.0.1, I m also in need of the 2.0.4 APK to keep going until issue is solved

**Comment by macemoneta** [comment]
Same here. The update needs to be backed out until it's corrected.

**Comment by landstander668** [comment]
Google Play just made an update (which is actually a downgrade to 2.0.4) available to me, for the second time today. This one, unlike the earlier downgrade, appears to be working normally. :)

**Comment by bpellin** [comment]
What was the file path you were using when you get this error?

**Comment by michaelwoods** [comment]
Both /mnt/sdcard/... and /sdcard/... failed for me.

**Comment by bpellin** [comment]
I believe I have fixed this in the latest beta. Can you try it and see if it works correctly for you?
https://play.google.com/apps/testing/com.android.keepass

**Comment by landstander668** [comment]
I just updated to 2.0.5beta5 via Google Play, and unfortunately it's still reporting "read failed: EBADF (Bad file descriptor)" when I try to open a kdbx file.

**Comment by bpellin** [comment]
How do you open the file? Starting from another app, from the browse folder
within Keepassdroid, which other app? What is the path that it tries to
open?

**Comment by landstander668** [comment]
I'm trying to open it directly from KeePassDroid, which is using the remembered filenames (so no manually typing or use of the browser). The only visible difference from version 2.0.4 is that the paths are now prefixed by "file://", but I don't _think_ that's relevant to this issue.

The paths in question are:

file:///sdcard/keepass/adric.kdbx
file:///sdcard/keepass-private/adric.key

**Comment by bpellin** [comment]
Thanks that helps a lot. There's still something wrong with keyfiles. I'll
try to get it fixed tonight.

**Comment by bpellin** [comment]
This should be fixed in 2.0.5beta6.

**Comment by landstander668** [comment]
Confirmed... version 2.0.5beta6 was able to open all 3 of my kdbx files, each of which has a different keyfile. :) While I haven't tried creating or editing an entry yet, all appears well in basic usage.

**Comment by bpellin** [comment]
This should be fixed in 2.0.6 which is rolling out now.
