### ISSUE TITLE
After installing latest update which is actually a downgrade to 2.0.4 Keepassdroid no longer opens

### ISSUE THREAD

**Issue by redsnapper8t8** [bpellin/keepassdroid#83]
After installing latest update which is actually a downgrade to 2.0.4 Keepassdroid no longer opens.

I have tried restarting phone and uninstalling and reinstalling keepassdroid. App still fails to open.

Running android 5 on Samsung SM-N9005

**Comment by landstander668** [comment]
Same here. As soon as I tap the icon I get "Unfortunately, KeePassDroid has stopped".

Nexus 6P running stock Android 6.0.1 (February security update).

**Comment by scasagrande-d2l** [comment]
+1

**Comment by landstander668** [comment]
I've attached a logcat for this issue.
[logcat.txt](https://github.com/bpellin/keepassdroid/files/163586/logcat.txt)

**Comment by JediLin** [comment]
+1
Nexus 7 (2nd Gen) w/ Android 4.3

**Comment by landstander668** [comment]
Just to reiterate what the original poster stated, this issue persists after clearing app data, and even after uninstalling/reinstalling the app. So reverting to version 2.0.4 actually seems to have made the situation slightly worse.

Was the downgrade accomplished using the original 2.0.4 APK, or was it a rebuilt version?

**Comment by Spaceman-Spliff** [comment]
+1
Nexus 5, 6.0.1

**Comment by bl4nk** [comment]
Same here, Galaxy S6 on 5.1.1

**Comment by DragonDon** [comment]
Iiiii think I'll wait and not update any time soon.....sorry to hear your
having such issues with this update Brian.  This is such a great product
and hopefully things get cleared up soon for you.

On Tue, Mar 8, 2016 at 12:58 PM bl4nk <notifications@github.com> wrote:

> Same here, Galaxy S6 on 5.1.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bpellin/keepassdroid/issues/83#issuecomment-193891675>
> .
>
-- 
*DragonDon*
Web: http://bluejeanstech.com
LinkedIn: https://ca.linkedin.com/in/dragondonbelmore
Google+: http://google.com/+Bluejeanstech
Skype: dragndon

**Comment by mactep3230** [comment]
reinstall version 2.0.5 , the database was opened . This makes me happy. Why was downgrade?

**Comment by landstander668** [comment]
Google Play just presented me with an update, which is also a downgrade to 2.0.4. This one, unlike the original downgrade, appears to be working normally. :)

**Comment by bl4nk** [comment]
Yup, the new update launches again. Thanks, Brian!

**Comment by scasagrande-d2l** [comment]
Fixed! :+1: :tada:
