### ISSUE TITLE
Android N compatibility: HashedBlockInputStream.read() returned value out of range

### ISSUE THREAD

**Issue by kbrosnan** [bpellin/keepassdroid#86]
Install Android N developer preview. Launch Keepass. Upon unlocking I see the following error.

    com.keepassdroid.stream.HashedBlockInputStream.read() returned value out of range -1..255: -117

Database does not open.

**Comment by bpellin** [comment]
I believe I have fixed this in the latest beta. Please try it and let me know if it works:
https://play.google.com/apps/testing/com.android.keepass

**Comment by kbrosnan** [comment]
Yes using the beta release unlocks the database. Thank you!

**Comment by mikeluby** [comment]
Works for me too, thanks!

**Comment by bpellin** [comment]
This should be fixed in 2.0.6 which is rolling out now.
