### ISSUE TITLE
This file type is unsupported (android)

### ISSUE THREAD

**Issue by nolliug** [bpellin/keepassdroid#88]
Hello I use a .kdb database which is hosted on Google Drive. It remains in grey when I want to open it. Same if I choose "available offline". It worked before the Google Update.What can I do to read my kdb file on Android?

**Comment by acertain** [comment]
If you install FX file browser, you can open it via that. Download the file and then browse to your downloads folder.

**Comment by nolliug** [comment]
It works now (don't ask me how) but for those who have that same problem, I suggest to install the program and try twice: it did not work the first time for me. I am not sure but I think the program needs to crawl or do something. Thank you.

**Comment by nolliug** [comment]
Is there another program to replace KeepassDroid and which works with Drive?
