### ISSUE TITLE
Can't open database file except .kbdx extension

### ISSUE THREAD

**Issue by VictoRXC** [bpellin/keepassdroid#91]
Because of security I keep my database in file with extension that not .kbdx. KeePassDroid can not open it. But Keepass2Android can do it.

**Comment by MoHf7f4** [comment]
I'm having same problem with .kbd files.  Android doesn't let me open them by selecting them.

**Comment by bpellin** [comment]
File selection should work much better in the latest beta if you want to try it:
https://play.google.com/apps/testing/com.android.keepass

**Comment by VictoRXC** [comment]
Done. "Unfortunately KeePassDroid has stopped." I've sent the log.

**Comment by jpgaribotti** [comment]
I'm oddly having the exact opposite problem. I've been using KeePassDroid for a while, it's always worked just fine. I could open the kdbx database straight from the Google Drive app. Today I tried to open it and I could no longer open kdbx files. Not even by browsing directly from the app. Everything appeared greyed out and wouldn't let me select it.

I tried it with Keepass2android and it was fine, so it doesn't seem like the db was broken.

**Comment by MoHf7f4** [comment]
The beta allows me to select the file, and open file directly.  Nice work!

**Comment by nolliug** [comment]
When is it going to work for .kdb files on Android 6? They remain in grey, can't be opened.

**Comment by bpellin** [comment]
This should be fixed in 2.0.6 which is rolling out now.

**Comment by VictoRXC** [comment]
Fixed. Thanks.

**Comment by nolliug** [comment]
Works now.
Thanks.
