### ISSUE TITLE
Readme for building source is not up to date

### ISSUE THREAD

**Issue by lanpirot** [bpellin/keepassdroid#97]
The version beforehand stated, how to build the src-files with the android-ndk. However since the latest update you cannot execute android-ndk from the keepassdroid-root-directory.
Executing it from the "/app/src/main/jni"-directory does stuff, but doesn't build the source, as far as I can gather it.

So either the readme needs to be updated, or there are is a Android.mk files missing in the root-folder?

**Comment by bpellin** [comment]
I make some updates. Everything just builds with gradle now.
