### ISSUE TITLE
Can't open databases Android 6

### ISSUE THREAD

**Issue by jczzz1** [bpellin/keepassdroid#98]
Hi

I've got two phones, a Nexus 6 and a Nexus 5x, both with 6.0.1 March 1, 2016 security level.

On the Nexus 6 I've got keepassandroid v2.04 released March 8.
On the Nexus 5x I still have 2.05, that was briefly released before being dropped to 2.04 (I've not updated it yet)

On the Nexus 6, v2.04 I can't open any files kdbx files from either Google drive or my download folder.
I've cleared cache, uninstall/ install and problem remains.

On the Nexus 5x with v2.05 I don't have problems with the same scenario.

This is identical of the issue previously reported and that people said it was fixed on the 8th March version. However I noticed that they mentioned using Android 5.0

I'm wondering if this is specific to Android 6.0?

If you need any logs and let me know how to do it, I'll be willing to help.

I use this program a lot and it's excellent.. Keep up the awesome work!

Jose

**Comment by bpellin** [comment]
This should all be cleaned up with v2.0.6 which is rolling out now.
